Fixed:
  1) get jobs should never be empty since jobs are seeded:
       MissingSchemaError: Schema hasn't been registered for model
       "Job".
       Use mongoose.model(name, schema)